networks:
  escalante-net:
    driver: bridge

volumes:
  blacklist-data:
    name: blacklist-data

services:
  blacklist-redis:
    container_name: escalante-blacklist
    image: redis:8.4.0-bookworm
    restart: unless-stopped
    volumes:
      - blacklist-data:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - escalante-net
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M

  api:
    container_name: escalante-api
    build:
      context: ./apis
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - FRONT_URL=${FRONT_URL}
      - PROFILE_ACTIVE=${PROFILE_ACTIVE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - USUARIO_INICIAL_USERNAME=${USUARIO_INICIAL_USERNAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      blacklist-redis:
        condition: service_healthy
    networks:
      - escalante-net
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G

  front:
    container_name: escalante-front
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - SERVER_NAME=${SERVER_NAME}
      - API_URL=${API_URL}
    depends_on:
      - api
    networks:
      - escalante-net
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M