networks:
  escalante-net:
    driver: bridge

volumes:
  blacklist-data:
    name: blacklist-data
  pgdata:
    name: pgdata

services:
  db:
    container_name: escalante-db
    image: postgres:17-trixie
    user: postgres
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - TZ=${TZ}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      start_period: 1m
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - escalante-net
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G

  blacklist-redis:
    container_name: escalante-blacklist
    image: redis:8.4.0-bookworm
    restart: unless-stopped
    volumes:
      - blacklist-data:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      start_period: 1m
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - escalante-net
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M

  api:
    container_name: escalante-api
    build:
      context: ./apis
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - FRONT_URL=${FRONT_URL}
      - PROFILE_ACTIVE=${PROFILE_ACTIVE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - USUARIO_INICIAL_USERNAME=${USUARIO_INICIAL_USERNAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
    depends_on:
      blacklist-redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - escalante-net
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G

  front:
    container_name: escalante-front
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - SERVER_NAME=${SERVER_NAME}
      - API_URL=${API_URL}
    depends_on:
      - api
    networks:
      - escalante-net
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M