spring:
  application:
    name: escalante
  profiles:
    active:
    - ${PROFILE_ACTIVE:dev}
logging:
  level:
    org:
      springframework:
        web:
          method:
            annotation:
              ExceptionHandlerExceptionResolver: OFF
          servlet:
            mvc:
              method:
                annotation:
                  ExceptionHandlerExceptionResolver: OFF
env:
  front:
    url: ${FRONT_URL:http://localhost:*}