spring:
  application:
    name: escalante-api
  profiles:
    active:
      - ${PROFILE_ACTIVE}
  jpa:
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      timeout: 5s
logging:
  level:
    org:
      springframework:
        web:
          method:
            annotation:
              ExceptionHandlerExceptionResolver: OFF
          servlet:
            mvc:
              method:
                annotation:
                  ExceptionHandlerExceptionResolver: OFF
env:
  front:
    url: ${FRONT_URL}
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
  usuario:
    inicial:
      username: ${USUARIO_INICIAL_USERNAME}
