spring:
  application:
    name: escalante-api
  profiles:
    active:
    - ${PROFILE_ACTIVE}
  jpa:
    open-in-view: false
logging:
  level:
    org:
      springframework:
        web:
          method:
            annotation:
              ExceptionHandlerExceptionResolver: OFF
          servlet:
            mvc:
              method:
                annotation:
                  ExceptionHandlerExceptionResolver: OFF
env:
  front:
    url: ${FRONT_URL}
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
  usuario:
    inicial:
      username: ${USUARIO_INICIAL_USERNAME}
      password: ${USUARIO_INICIAL_PASSWORD}
    padrao:
      password: ${USUARIO_PADRAO_PASSWORD}