spring:
  application:
    name: escalante-api
  profiles:
    active:
    - ${PROFILE_ACTIVE:dev}
logging:
  level:
    org:
      springframework:
        web:
          method:
            annotation:
              ExceptionHandlerExceptionResolver: OFF
          servlet:
            mvc:
              method:
                annotation:
                  ExceptionHandlerExceptionResolver: OFF
env:
  front:
    url: ${FRONT_URL:http://localhost:*}
  jwt:
    secret: ${JWT_SECRET:7cadc739b1a4f4ba8639f78ad73cdf44f5fba0d5e513ced7199b540fd2c1f566}
    expiration: ${JWT_EXPIRATION:21600}